
modLoader="javafml" #mandatory

loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="MIT"

[[mods]] #mandatory

modId="threethreeminer" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Three Three Miner" #mandatory

logoFile="threethreeminer.png" #optional

credits="this wouldnt be possible without DShadowWolf, thank you!" #optional

authors="caittastic" #optional

description='''
me learning how to copy the destruction catalyst
'''

[[dependencies.threethreeminer]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[39,)" #mandatory

    ordering="NONE"

    side="BOTH"
# Here's another dependency
[[dependencies.threethreeminer]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
